// PhrenKit for Android: the pure-Kotlin port of apps/ios/PhrenKit. No Android
// dependencies, so the whole format/sync layer tests on a plain JVM.
plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    api(libs.coroutines.core)
    api(libs.serialization.json)
    api(libs.okhttp)
    // PhrenLive: SSH to each computer's Phren Hook (swift-nio-ssh on iOS).
    api(libs.sshj)
    api(libs.bouncycastle.prov)
    // One Bouncy Castle release across sshj's transitive modules.
    api(libs.bouncycastle.util)
    api(libs.bouncycastle.pkix)
    testImplementation(kotlin("test"))
    testImplementation(libs.junit)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.okhttp.mockwebserver)
}

// The fixtures are generated by the real CLI (apps/ios/scripts/generate-fixtures.mjs)
// and shared with the iOS tests: one source of truth, never copied.
sourceSets {
    test {
        resources.srcDir("../../ios/PhrenKit/Tests/PhrenKitTests")
    }
}

tasks.test {
    useJUnit()
}
