package com.phren.kit

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlin.test.fail

/**
 * The fixtures are the iOS ones (apps/ios/PhrenKit/Tests/PhrenKitTests/Fixtures),
 * generated by the real CLI via apps/ios/scripts/generate-fixtures.mjs and put
 * on the test classpath by phrenkit/build.gradle.kts — one source of truth.
 */
object Fixtures {
    fun text(name: String): String {
        val stream = Fixtures::class.java.classLoader.getResourceAsStream("Fixtures/$name")
            ?: fail("missing fixture $name")
        return stream.use { it.readBytes().toString(Charsets.UTF_8) }
    }

    fun json(name: String): JsonElement = Json.parseToJsonElement(text(name))
    fun array(name: String): List<JsonObject> = json(name).jsonArray.map { it.jsonObject }
}

fun JsonObject.str(key: String): String? = (this[key] as? JsonPrimitive)?.takeIf { it !is JsonNull && it.isString }?.content
fun JsonObject.bool(key: String): Boolean? = (this[key] as? JsonPrimitive)?.booleanOrNull
fun JsonObject.int(key: String): Int? = (this[key] as? JsonPrimitive)?.intOrNull
fun JsonObject.double(key: String): Double? = (this[key] as? JsonPrimitive)?.doubleOrNull
fun JsonObject.obj(key: String): JsonObject? = this[key] as? JsonObject
fun JsonObject.arr(key: String): JsonArray? = this[key] as? JsonArray

/** Byte-level comparison with a readable first-difference diagnostic. */
fun assertSameContent(actual: String, expected: String, label: String) {
    if (actual == expected) return
    val a = actual.split("\n")
    val e = expected.split("\n")
    for (i in 0 until maxOf(a.size, e.size)) {
        val al = a.getOrElse(i) { "<missing>" }
        val el = e.getOrElse(i) { "<missing>" }
        if (al != el) fail("$label: first difference at line ${i + 1}\n  actual:   $al\n  expected: $el")
    }
    fail("$label: contents differ (whitespace-only difference)")
}
