#!/usr/bin/env tsx
/**
 * Generate PHREN_ART truecolor constant from phren-transparent.png.
 *
 * Usage: npx tsx scripts/generate-phren-art.ts [width]
 *
 * Reads docs/phren-transparent.png, resizes to [width] (default 24),
 * and outputs the PHREN_ART array using half-block ▀ characters with
 * truecolor ANSI escape codes (38;2;R;G;B foreground, 48;2;R;G;B background).
 *
 * Each terminal character represents 2 vertical pixels:
 * - Top pixel = foreground color of ▀
 * - Bottom pixel = background color of ▀
 *
 * Pipe output into mcp/src/phren-art.ts to update the constant.
 */

import sharp from "sharp";
import path from "path";

const width = parseInt(process.argv[2] || "24", 10);
const pngPath = path.resolve(import.meta.dirname, "..", "docs", "phren-transparent.png");

async function generate() {
  const { data, info } = await sharp(pngPath)
    .resize(width, width, {
      kernel: "nearest", // preserve pixel-art crispness
      fit: "contain",
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .raw()
    .ensureAlpha()
    .toBuffer({ resolveWithObject: true });

  const { width: w, height: h } = info;
  const lines: string[] = [];

  for (let y = 0; y < h; y += 2) {
    let line = "";
    for (let x = 0; x < w; x++) {
      const ti = (y * w + x) * 4;
      const bi = Math.min(((y + 1) * w + x) * 4, data.length - 4);
      const topVisible = data[ti + 3] > 50;
      const botVisible = y + 1 < h && data[bi + 3] > 50;

      if (topVisible && botVisible) {
        const fg = `\\x1b[38;2;${data[ti]};${data[ti + 1]};${data[ti + 2]}m`;
        const bg = `\\x1b[48;2;${data[bi]};${data[bi + 1]};${data[bi + 2]}m`;
        line += `${fg}${bg}▀\\x1b[0m`;
      } else if (topVisible) {
        line += `\\x1b[38;2;${data[ti]};${data[ti + 1]};${data[ti + 2]}m▀\\x1b[0m`;
      } else if (botVisible) {
        line += `\\x1b[38;2;${data[bi]};${data[bi + 1]};${data[bi + 2]}m▄\\x1b[0m`;
      } else {
        line += " ";
      }
    }
    lines.push(line);
  }

  // Output as JS constant
  console.log("// Auto-generated by scripts/generate-phren-art.ts");
  console.log(`// Source: docs/phren-transparent.png @ ${width}x${width}`);
  console.log("// Regenerate: npx tsx scripts/generate-phren-art.ts");
  console.log("export const PHREN_ART = [");
  for (const line of lines) {
    console.log(`  ${JSON.stringify(line)},`);
  }
  console.log("];");
}

generate().catch(console.error);
