/**
 * Environment flags, onboarding preferences, and repair asset helpers for init.
 */
import * as fs from "fs";
import * as path from "path";
import * as crypto from "crypto";
import type { ProactivityLevel } from "./proactivity.js";
import type { WorkflowRiskSection } from "./init-walkthrough.js";
import type { InitOptions } from "./init-types.js";
import {
  writeInstallPreferences,
  writeGovernanceInstallPreferences,
} from "./preferences.js";
import { updateWorkflowPolicy } from "./governance.js";
import {
  repairPreexistingInstall,
  ensureGitignoreEntry,
  upsertProjectEnvVar,
} from "./setup.js";

export function applyOnboardingPreferences(phrenPath: string, opts: InitOptions): void {
  if (opts.projectOwnershipDefault) {
    writeInstallPreferences(phrenPath, { projectOwnershipDefault: opts.projectOwnershipDefault });
  }
  const runtimePatch: {
    proactivityFindings?: ProactivityLevel;
    proactivityTask?: ProactivityLevel;
  } = {};
  if (opts.findingsProactivity) runtimePatch.proactivityFindings = opts.findingsProactivity;
  if (opts.taskProactivity) runtimePatch.proactivityTask = opts.taskProactivity;
  if (Object.keys(runtimePatch).length > 0) {
    writeInstallPreferences(phrenPath, runtimePatch);
  }
  const governancePatch: {
    proactivityFindings?: ProactivityLevel;
    proactivityTask?: ProactivityLevel;
  } = {};
  if (opts.findingsProactivity) governancePatch.proactivityFindings = opts.findingsProactivity;
  if (opts.taskProactivity) governancePatch.proactivityTask = opts.taskProactivity;
  if (Object.keys(governancePatch).length > 0) {
    writeGovernanceInstallPreferences(phrenPath, governancePatch);
  }
  const workflowPatch: {
    lowConfidenceThreshold?: number;
    riskySections?: WorkflowRiskSection[];
    taskMode?: "off" | "manual" | "suggest" | "auto";
    findingSensitivity?: "minimal" | "conservative" | "balanced" | "aggressive";
  } = {};
  if (typeof opts.lowConfidenceThreshold === "number") workflowPatch.lowConfidenceThreshold = opts.lowConfidenceThreshold;
  if (Array.isArray(opts.riskySections)) workflowPatch.riskySections = opts.riskySections;
  if (opts.taskMode) workflowPatch.taskMode = opts.taskMode;
  if (opts.findingSensitivity) workflowPatch.findingSensitivity = opts.findingSensitivity;
  if (Object.keys(workflowPatch).length > 0) {
    updateWorkflowPolicy(phrenPath, workflowPatch);
  }
}

export function writeWalkthroughEnvDefaults(phrenPath: string, opts: InitOptions): string[] {
  const envFile = path.join(phrenPath, ".env");
  let envContent = fs.existsSync(envFile) ? fs.readFileSync(envFile, "utf8") : "# phren feature flags — generated by init\n";
  const envFlags: { flag: string; label: string }[] = [];
  const autoCaptureChoice = opts._walkthroughAutoCapture;
  const hasAutoCaptureFlag = /^\s*PHREN_FEATURE_AUTO_CAPTURE=.*$/m.test(envContent);
  if (typeof autoCaptureChoice === "boolean") {
    envFlags.push({
      flag: `PHREN_FEATURE_AUTO_CAPTURE=${autoCaptureChoice ? "1" : "0"}`,
      label: `Auto-capture ${autoCaptureChoice ? "enabled" : "disabled"}`,
    });
  } else if (!hasAutoCaptureFlag) {
    // Default to enabled on fresh installs and non-walkthrough init.
    envFlags.push({ flag: "PHREN_FEATURE_AUTO_CAPTURE=1", label: "Auto-capture enabled" });
  }
  if (opts._walkthroughSemanticDedup) envFlags.push({ flag: "PHREN_FEATURE_SEMANTIC_DEDUP=1", label: "Semantic dedup" });
  if (opts._walkthroughSemanticConflict) envFlags.push({ flag: "PHREN_FEATURE_SEMANTIC_CONFLICT=1", label: "Conflict detection" });

  if (envFlags.length === 0) return [];
  let changed = false;
  const enabledLabels: string[] = [];

  for (const { flag, label } of envFlags) {
    const key = flag.split("=")[0];
    const lineRe = new RegExp(`^\\s*${key}=.*$`, "m");
    if (lineRe.test(envContent)) {
      const before = envContent;
      envContent = envContent.replace(lineRe, flag);
      if (envContent !== before) {
        changed = true;
        enabledLabels.push(label);
      }
    } else {
      if (!envContent.endsWith("\n")) envContent += "\n";
      envContent += `${flag}\n`;
      changed = true;
      enabledLabels.push(label);
    }
  }

  if (changed) {
    const tmpPath = `${envFile}.tmp-${crypto.randomUUID()}`;
    fs.writeFileSync(tmpPath, envContent);
    fs.renameSync(tmpPath, envFile);
  }
  return enabledLabels.map((label) => `${label} (${envFile})`);
}

export function collectRepairedAssetLabels(repaired: ReturnType<typeof repairPreexistingInstall>): string[] {
  const repairedAssets: string[] = [];
  if (repaired.createdContextFile) repairedAssets.push("~/.phren-context.md");
  if (repaired.createdRootMemory) repairedAssets.push("generated MEMORY.md");
  repairedAssets.push(...repaired.createdGlobalAssets);
  repairedAssets.push(...repaired.createdRuntimeAssets);
  repairedAssets.push(...repaired.createdFeatureDefaults);
  repairedAssets.push(...repaired.createdSkillArtifacts);
  return repairedAssets;
}

export function applyProjectStorageBindings(repoRoot: string, phrenPath: string): string[] {
  const updates: string[] = [];
  if (ensureGitignoreEntry(repoRoot, ".phren/")) {
    updates.push(`${path.join(repoRoot, ".gitignore")} (.phren/)`);
  }
  if (upsertProjectEnvVar(repoRoot, "PHREN_PATH", phrenPath)) {
    updates.push(`${path.join(repoRoot, ".env")} (PHREN_PATH=${phrenPath})`);
  }
  return updates;
}
