import XCTest
@testable import PhrenKit

/// Fixtures here are written by hand (not generated by the CLI) since
/// `stores.yaml` is a registry file, not markdown the CLI's own parser tests
/// already cover — see StoresManifest.swift's doc comment for the shape this
/// mirrors (packages/cli/src/store-registry.ts).
final class StoresManifestTests: XCTestCase {
    private let sample = """
    version: 1
    stores:
      - id: 365c6bb8
        name: phren
        path: ~/.phren
        role: primary
        sync: managed-git
      - id: 67d3e4c9
        name: work-shared
        path: ~/.phren-work-shared
        role: team
        sync: managed-git
        projects:
          - alpha
          - beta
    """

    func testParsesExampleRegistry() {
        let manifest = StoresManifest.parse(sample)
        XCTAssertEqual(manifest.stores.count, 2)

        let primary = manifest.stores[0]
        XCTAssertEqual(primary.id, "365c6bb8")
        XCTAssertEqual(primary.name, "phren")
        XCTAssertEqual(primary.role, "primary")
        XCTAssertTrue(primary.isPrimary)
        XCTAssertEqual(primary.projects, [])

        let team = manifest.stores[1]
        XCTAssertEqual(team.id, "67d3e4c9")
        XCTAssertEqual(team.name, "work-shared")
        XCTAssertEqual(team.role, "team")
        XCTAssertFalse(team.isPrimary)
        XCTAssertEqual(team.projects, ["alpha", "beta"])
    }

    func testClaimingEntryFlagsAProjectLeakedIntoTheWrongStore() {
        let manifest = StoresManifest.parse(sample)

        // "alpha" physically sitting in the "phren" (primary) store is a leak —
        // the registry says it belongs to "work-shared".
        let claim = manifest.claimingEntry(for: "alpha", physicalStoreName: "phren")
        XCTAssertEqual(claim?.name, "work-shared")

        // "alpha" physically sitting in "work-shared" itself is correct —
        // no claim against its own store.
        XCTAssertNil(manifest.claimingEntry(for: "alpha", physicalStoreName: "work-shared"))
        // Folded from testClaimingEntryIsNilForUnclaimedProjects.
        do {
            let manifest = StoresManifest.parse(sample)
            XCTAssertNil(manifest.claimingEntry(for: "unrelated-project", physicalStoreName: "phren"))
        }
    }

    func testClaimingEntryNeverMatchesThePrimaryRole() {
        // Defensive: even if a primary entry somehow carried a projects list,
        // it must never "claim" a project away from another store.
        let manifest = StoresManifest(stores: [
            .init(name: "phren", role: "primary", projects: ["gamma"]),
            .init(name: "work-shared", role: "team", projects: []),
        ])
        XCTAssertNil(manifest.claimingEntry(for: "gamma", physicalStoreName: "work-shared"))
    }

    func testReadonlyRoleAlsoCounts() {
        let manifest = StoresManifest(stores: [
            .init(name: "phren", role: "primary"),
            .init(name: "archive", role: "readonly", projects: ["old-project"]),
        ])
        XCTAssertEqual(manifest.claimingEntry(for: "old-project", physicalStoreName: "phren")?.name, "archive")
    }

    func testUnknownTopLevelAndEntryKeysAreIgnored() {
        let content = """
        version: 1
        stores:
          - id: aaaa1111
            name: phren
            path: ~/.phren
            role: primary
            sync: managed-git
            remote: git@github.com:me/phren.git
        futureTopLevelKey:
          nested: true
        """
        let manifest = StoresManifest.parse(content)
        XCTAssertEqual(manifest.stores.count, 1)
        XCTAssertEqual(manifest.stores[0].name, "phren")
        XCTAssertEqual(manifest.stores[0].role, "primary")
    }

    func testMissingStoresKeyYieldsEmptyManifest() {
        XCTAssertEqual(StoresManifest.parse("version: 1\n").stores, [])
        // Folded from testEmptyContentYieldsEmptyManifest.
        do {
            XCTAssertEqual(StoresManifest.parse("").stores, [])
        }
    }

    func testEntryMissingNameIsSkipped() {
        let content = """
        version: 1
        stores:
          - id: aaaa1111
            role: primary
            sync: managed-git
          - id: bbbb2222
            name: work-shared
            role: team
            projects:
              - gamma
        """
        let manifest = StoresManifest.parse(content)
        XCTAssertEqual(manifest.stores.map(\.name), ["work-shared"])
    }

    func testCRLFLineEndingsParseIdentically() {
        let crlf = sample.replacingOccurrences(of: "\n", with: "\r\n")
        XCTAssertEqual(StoresManifest.parse(crlf), StoresManifest.parse(sample))
    }

    func testFlowStyleProjectsListIsAccepted() {
        let content = """
        version: 1
        stores:
          - id: 67d3e4c9
            name: work-shared
            role: team
            projects: [alpha, beta]
        """
        let manifest = StoresManifest.parse(content)
        XCTAssertEqual(manifest.stores.first?.projects, ["alpha", "beta"])
    }

    func testThreeEntryRegistryPreservesOrderAndEachProjectsList() {
        let content = """
        version: 1
        stores:
          - id: 1
            name: phren
            role: primary
          - id: 2
            name: work-shared
            role: team
            projects:
              - alpha
          - id: 3
            name: archive
            role: readonly
            projects:
              - legacy-one
              - legacy-two
        """
        let manifest = StoresManifest.parse(content)
        XCTAssertEqual(manifest.stores.map(\.name), ["phren", "work-shared", "archive"])
        XCTAssertEqual(manifest.stores[1].projects, ["alpha"])
        XCTAssertEqual(manifest.stores[2].projects, ["legacy-one", "legacy-two"])
    }
}
